name: "Run CI"

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure
        run: cmake -S . -B .build -DCMAKE_BUILD_TYPE=Debug -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=ON

      - name: Building
        run: cd .build && make -j $(nproc)

      - name: Running
        run: cd .build && make test

  examples:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure
        run: cmake -S . -B .build -DCMAKE_BUILD_TYPE=Debug -DBUILD_EXAMPLES=ON -DBUILD_TESTING=OFF

      - name: Building
        run: cd .build && make -j $(nproc)
